project:
  type: website
  pre-render:
    - scripts/pre_create_papers_file.py
    # - scripts/pre_check_skierg_records.py
    # - scripts/pre_doi_from_rogue_scholar.py
    # - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  title: "Emilyn Costa"
  description: "Emilyn Costa is a biologist/microbiologist working at the intersection of genomics, epidemiology and public health."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV
        text: CV
      - href: posts
        text: Blog
      - href: ignite
        text: IGNITE
#      - href: papers
#        text: Papers
#      - href: media
#        text: Media
#      - href: talks
#        text: Talks
      - href: https://www.amazon.com.br/Revis%C3%A3o-Sobre-Tuberculose-Emilyn-Concei%C3%A7%C3%A3o-ebook/dp/B07DVP9JNL/ref=sr_1_21?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=U31S1O2KCKCK&dib=eyJ2IjoiMSJ9.MxDECZeff-uDDxX_6AypQWYXp1A_ufJx627I6gJqWbO9ThB4d3Fi_j92s6H7LHtloBoAnKyltswW-2CgJT4hjvq6bmluOWILR7Y0Jyy3TaIVDQYha1ZXE01tz0CqEHpNqoAVTwqL3dqqWBK3d0hO9dW_-YI7XCGiZX5tBQtIPpKKIn9ATzp7kWoeuZYp9_dTjnY_WQhg0n1eWI5-A7Kx84WGg3HQYzrIcsvLJBikSa2LiRqZNeu3WTAOiHUg12Lg--bl1S1lq-TbzLdYfdsp9nZBVQlCONmFhTeJmCRKGRQ.j-DVS2kLrIKVaP0omIf-OlWOQvVcRazLYa5xaev5bgM&dib_tag=se&keywords=tuberculose&qid=1745342291&sprefix=tuberculose%2Caps%2C487&sr=8-21
        text: My book
  
  page-footer:
    left: "(c) Emilyn Costa, 2025–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Emilyn Costa","jobTitle":"","height":" inches","gender":"female","description":"Emilyn Costa is a ","url":"https://emilyncosta.com","image":"https://emilyncosta.com/img/IMG_5986.jpeg","address":{"@type":"PostalAddress","addressLocality":"","addressRegion":"","postalCode":"","addressCountry":""},"alumniOf":[{"@type":"CollegeOrUniversity","name":"","sameAs":"https://en.wikipedia.org/wiki/University_of_Oxford"},{"@type":"CollegeOrUniversity","name":"Cardiff University","sameAs":"https://en.wikipedia.org/wiki/Cardiff_University"}],"worksFor":[{"@type":"Organization","name":"HCLTech"}],"birthDate":"1986-07-15","birthPlace":"Budapest, Hungary","memberOf":[{"@type":"Organization","name":"Royal Society for Public Health"},{"@type":"Organization","name":"TOPRA"},{"@type":"Organization","name":"IEEE"}],"nationality":[{"@type":"Country","name":"United Kingdom"},{"@type":"Country","name":"Hungary"}]}</script>



