project:
  type: website
  output-dir: _site
  #lib-dir: assets_web
  #pre-render:
  # - scripts/pre_create_papers_file.py
  # - scripts/pre_check_skierg_records.py
  # - scripts/pre_doi_from_rogue_scholar.py
  # - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  title: "Abhinav Sharma"
  description: "Abhinav Sharma is a data scientist working at the intersection of genomics, machine learning and public health."
  navbar:
    left:
      - href: index.qmd
        text: Home
  #      - href: CV
  #        text: CV
  #      - href: posts
  #        text: Blog
  #      - href: papers
  #        text: Papers
  #      - href: media
  #        text: Media
  #      - href: talks
  #        text: Talks
  page-footer:
    left: "(c) Abhinav Sharma, 2025–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  #  google-analytics: "395640625"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Abhinav Sharma","jobTitle":"","height":" inches","gender":"female","description":"Abhinav Sharma is a ","url":"https://abhi18av.com","image":"https://abhi18av.com/img/IMG_5986.jpeg","address":{"@type":"PostalAddress","addressLocality":"","addressRegion":"","postalCode":"","addressCountry":""},"alumniOf":[{"@type":"CollegeOrUniversity","name":"","sameAs":"https://en.wikipedia.org/wiki/University_of_Oxford"},{"@type":"CollegeOrUniversity","name":"Cardiff University","sameAs":"https://en.wikipedia.org/wiki/Cardiff_University"}],"worksFor":[{"@type":"Organization","name":"Stellenbosch University"}],"birthDate":"1993-03-29","birthPlace":"New Delhi, India","memberOf":[{"@type":"Organization","name":"Royal Society for Public Health"},{"@type":"Organization","name":"TOPRA"},{"@type":"Organization","name":"IEEE"}],"nationality":[{"@type":"Country","name":"India}]}</script>
