name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: cp website_config.json.copy website_config.json
    # - run: sed -i "s%TRACKING_ID_VALUE%${{ secrets.TRACKING_ID }}%g" website_config.json
    # - run: sed -i "s%MAILCHIMP_URL_VALUE%${{ secrets.MAILCHIMP_URL }}%g" website_config.json # seperator is % to prevent issues with the URL
    - run: npm run build
